# Generated by Django 4.2.1 on 2023-05-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('custumer_name', models.CharField(max_length=255)),
                ('custumer_email', models.EmailField(max_length=254)),
                ('custumer_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
